//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GherasEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int ID { get; set; }
        public string Certificate_name { get; set; }
        public string University_name { get; set; }
        public Nullable<System.DateTime> Graduation { get; set; }
        public string Study_year { get; set; }
        public int User_ID { get; set; }
    
        public virtual Job_seeker Job_seeker { get; set; }
    }
}
