//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GherasEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hired
    {
        public int Company_ID { get; set; }
        public int User_ID { get; set; }
        public int Vacancy_ID { get; set; }
        public string Hire_date { get; set; }
        public string notes { get; set; }
    
        public virtual company company { get; set; }
        public virtual Job_seeker Job_seeker { get; set; }
        public virtual Vacancy Vacancy { get; set; }
    }
}
