//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GherasEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_seeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job_seeker()
        {
            this.Certificate = new HashSet<Certificate>();
            this.courses = new HashSet<courses>();
            this.Hired = new HashSet<Hired>();
            this.Language = new HashSet<Language>();
            this.References = new HashSet<References>();
            this.Skills = new HashSet<Skills>();
            this.User_Job = new HashSet<User_Job>();
            this.Work_For = new HashSet<Work_For>();
        }
    
        public string First_name { get; set; }
        public string Second_name { get; set; }
        public string Father_name { get; set; }
        public string Mother_Fname { get; set; }
        public string Mother_Lname { get; set; }
        public string Place_Of_Birth { get; set; }
        public string National_ID { get; set; }
        public string PersonalCard_number { get; set; }
        public int Gender { get; set; }
        public string Face_Color { get; set; }
        public string eyes_Color { get; set; }
        public string Current_address { get; set; }
        public string Previous_address { get; set; }
        public string special_Mark { get; set; }
        public string Date_Of_Release { get; set; }
        public string Military_service { get; set; }
        public string Social_status { get; set; }
        public int Driving_license { get; set; }
        public int Has_car { get; set; }
        public int Smoking { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string mobile { get; set; }
        public string Handicap { get; set; }
        public string Extra_Information { get; set; }
        public string municipality { get; set; }
        public string registration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificate> Certificate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<courses> courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hired> Hired { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Language> Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<References> References { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Skills> Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Job> User_Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Work_For> Work_For { get; set; }
    }
}
