//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GherasEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int ID { get; set; }
        public string Language1 { get; set; }
        public string language_level { get; set; }
        public int User_ID { get; set; }
    
        public virtual Job_seeker Job_seeker { get; set; }
    }
}
