//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GherasEO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_For
    {
        public int ID { get; set; }
        public string Company_Name { get; set; }
        public string Company_plcae { get; set; }
        public string Field_Of_Work { get; set; }
        public string Job_Title { get; set; }
        public System.DateTime Hire_date { get; set; }
        public Nullable<System.DateTime> Quti_date { get; set; }
        public string Reason { get; set; }
        public int User_ID { get; set; }
    
        public virtual Job_seeker Job_seeker { get; set; }
    }
}
